using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FSSRC_DataMigration.DestinationEntity
{
    public class AssistedWith : BaseLookupEntity
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public virtual List<CounselingActivitiesAssistedWith> CounselingActivitiesAssistedWith { get; set; } = new List<CounselingActivitiesAssistedWith>();
    }

    class AssistedWithConfig : IEntityTypeConfiguration<AssistedWith>
    {
        public void Configure(EntityTypeBuilder<AssistedWith> entity)
        {
            entity.HasData(
                new AssistedWith { Id = 1, Code = "﻿1", Description = "Outreach", Enabled = false, DisplayOrder = 1 },
                new AssistedWith { Id = 2, Code = "2", Description = "Counseling", Enabled = false, DisplayOrder = 2 },
                new AssistedWith { Id = 3, Code = "3", Description = "Elder Abuse", Enabled = true, DisplayOrder = 3 },
                new AssistedWith { Id = 4, Code = "4", Description = "Transportation", Enabled = true, DisplayOrder = 4 },
                new AssistedWith { Id = 5, Code = "5", Description = "Meals on Wheels", Enabled = false, DisplayOrder = 5 },
                new AssistedWith { Id = 6, Code = "6", Description = "Reassurance Calling", Enabled = true, DisplayOrder = 6 },
                new AssistedWith { Id = 7, Code = "7", Description = "Friendly visitor", Enabled = false, DisplayOrder = 7 },
                new AssistedWith { Id = 8, Code = "8", Description = "HomeCare Private Pay", Enabled = true, DisplayOrder = 8 },
                new AssistedWith { Id = 9, Code = "9", Description = "Lions Club", Enabled = false, DisplayOrder = 9 },
                new AssistedWith { Id = 10, Code = "10", Description = "Rent assistance", Enabled = true, DisplayOrder = 10 },
                new AssistedWith { Id = 11, Code = "11", Description = "Utility assistance", Enabled = true, DisplayOrder = 11 },
                new AssistedWith { Id = 12, Code = "12", Description = "Prescription assistance", Enabled = true, DisplayOrder = 12 },
                new AssistedWith { Id = 13, Code = "13", Description = "Food assistance", Enabled = true, DisplayOrder = 13 },
                new AssistedWith { Id = 14, Code = "14", Description = "First Call for Help-other", Enabled = false, DisplayOrder = 14 },
                new AssistedWith { Id = 15, Code = "15", Description = "Food for Seniors", Enabled = false, DisplayOrder = 15 },
                new AssistedWith { Id = 16, Code = "16", Description = "Volunteer opportunity", Enabled = true, DisplayOrder = 16 },
                new AssistedWith { Id = 17, Code = "17", Description = "Caregiver Advisory Service-Caregiver", Enabled = true, DisplayOrder = 17 },
                new AssistedWith { Id = 18, Code = "18", Description = "Caregiver Advisory Service-GRG", Enabled = true, DisplayOrder = 18 },
                new AssistedWith { Id = 19, Code = "19", Description = "Self-Help Center", Enabled = false, DisplayOrder = 19 },
                new AssistedWith { Id = 20, Code = "20", Description = "Adult day care", Enabled = true, DisplayOrder = 20 },
                new AssistedWith { Id = 21, Code = "21", Description = "Homemaker", Enabled = false, DisplayOrder = 21 },
                new AssistedWith { Id = 22, Code = "22", Description = "Home repair", Enabled = true, DisplayOrder = 22 },
                new AssistedWith { Id = 23, Code = "23", Description = "CCU-other", Enabled = false, DisplayOrder = 23 },
                new AssistedWith { Id = 24, Code = "24", Description = "Homestead exemption", Enabled = false, DisplayOrder = 24 },
                new AssistedWith { Id = 25, Code = "25", Description = "Tax deferral program", Enabled = false, DisplayOrder = 25 },
                new AssistedWith { Id = 26, Code = "26", Description = "Tax freeze", Enabled = false, DisplayOrder = 26 },
                new AssistedWith { Id = 27, Code = "27", Description = "Food Pantry", Enabled = false, DisplayOrder = 27 },
                new AssistedWith { Id = 28, Code = "28", Description = "Transportation", Enabled = false, DisplayOrder = 28 },
                new AssistedWith { Id = 29, Code = "29", Description = "Gap filling", Enabled = false, DisplayOrder = 29 },
                new AssistedWith { Id = 30, Code = "30", Description = "Ombudsman", Enabled = false, DisplayOrder = 30 },
                new AssistedWith { Id = 31, Code = "31", Description = "Farmers' Market Coupons", Enabled = false, DisplayOrder = 31 },
                new AssistedWith { Id = 32, Code = "32", Description = "Food", Enabled = false, DisplayOrder = 32 },
                new AssistedWith { Id = 33, Code = "33", Description = "Money", Enabled = false, DisplayOrder = 33 },
                new AssistedWith { Id = 34, Code = "34", Description = "Furniture/Clothes", Enabled = true, DisplayOrder = 34 },
                new AssistedWith { Id = 35, Code = "35", Description = "Food", Enabled = false, DisplayOrder = 35 },
                new AssistedWith { Id = 36, Code = "36", Description = "Holiday program", Enabled = true, DisplayOrder = 36 },
                new AssistedWith { Id = 37, Code = "37", Description = "Fraternal Order of Police-Other", Enabled = false, DisplayOrder = 37 },
                new AssistedWith { Id = 38, Code = "38", Description = "Senior apartments", Enabled = true, DisplayOrder = 38 },
                new AssistedWith { Id = 39, Code = "39", Description = "Section 8 vouchers", Enabled = false, DisplayOrder = 39 },
                new AssistedWith { Id = 40, Code = "40", Description = "AABD CASH/Link card", Enabled = false, DisplayOrder = 40 },
                new AssistedWith { Id = 41, Code = "41", Description = "Food Stamps/Link card", Enabled = true, DisplayOrder = 41 },
                new AssistedWith { Id = 42, Code = "42", Description = "Qualified Medicare Beneficiary (QMB) or SLIB", Enabled = true, DisplayOrder = 42 },
                new AssistedWith { Id = 43, Code = "43", Description = "Medicaid application/re-certification", Enabled = true, DisplayOrder = 43 },
                new AssistedWith { Id = 44, Code = "44", Description = "Medicaid Spend-down assistance", Enabled = false, DisplayOrder = 44 },
                new AssistedWith { Id = 45, Code = "45", Description = "Medicaid Spousal Impoverishment", Enabled = false, DisplayOrder = 45 },
                new AssistedWith { Id = 46, Code = "46", Description = "Circuit Breaker-grant/tax relief", Enabled = false, DisplayOrder = 46 },
                new AssistedWith { Id = 47, Code = "47", Description = "Circuit Breaker-pharmaceutical card", Enabled = false, DisplayOrder = 47 },
                new AssistedWith { Id = 48, Code = "48", Description = "Congregate meal site", Enabled = false, DisplayOrder = 48 },
                new AssistedWith { Id = 49, Code = "49", Description = "Home-delivered meals", Enabled = false, DisplayOrder = 49 },
                new AssistedWith { Id = 50, Code = "50", Description = "Warm Neighbors", Enabled = false, DisplayOrder = 50 },
                new AssistedWith { Id = 51, Code = "51", Description = "Holiday voucher", Enabled = false, DisplayOrder = 51 },
                new AssistedWith { Id = 52, Code = "52", Description = "Social services", Enabled = false, DisplayOrder = 52 },
                new AssistedWith { Id = 53, Code = "53", Description = "Elder Care", Enabled = false, DisplayOrder = 53 },
                new AssistedWith { Id = 54, Code = "54", Description = "Home repair", Enabled = false, DisplayOrder = 54 },
                new AssistedWith { Id = 55, Code = "55", Description = "Money management", Enabled = true, DisplayOrder = 55 },
                new AssistedWith { Id = 56, Code = "56", Description = "Rural transportation", Enabled = false, DisplayOrder = 56 },
                new AssistedWith { Id = 57, Code = "57", Description = "Senior Services- other", Enabled = false, DisplayOrder = 57 },
                new AssistedWith { Id = 58, Code = "58", Description = "Social Security (SSA): Retirement", Enabled = true, DisplayOrder = 58 },
                new AssistedWith { Id = 59, Code = "59", Description = "Social Security (SSA): Disability", Enabled = true, DisplayOrder = 59 },
                new AssistedWith { Id = 60, Code = "60", Description = "Supplemental Security Income (SSI): 65+", Enabled = true, DisplayOrder = 60 },
                new AssistedWith { Id = 61, Code = "61", Description = "Supplemental Security Income (SSI): Disability", Enabled = true, DisplayOrder = 61 },
                new AssistedWith { Id = 62, Code = "62", Description = "Medicare", Enabled = false, DisplayOrder = 62 },
                new AssistedWith { Id = 63, Code = "63", Description = "Appeal", Enabled = false, DisplayOrder = 63 },
                new AssistedWith { Id = 64, Code = "64", Description = "Senior Employment Program", Enabled = true, DisplayOrder = 64 },
                new AssistedWith { Id = 65, Code = "65", Description = "Seniors in Community Service Program", Enabled = false, DisplayOrder = 65 },
                new AssistedWith { Id = 66, Code = "66", Description = "LIHEAP", Enabled = true, DisplayOrder = 66 },
                new AssistedWith { Id = 67, Code = "67", Description = "Weatherization/furnace repair", Enabled = true, DisplayOrder = 67 },
                new AssistedWith { Id = 68, Code = "68", Description = "Alzheimer's Association", Enabled = false, DisplayOrder = 68 },
                new AssistedWith { Id = 69, Code = "69", Description = "Housing (private)-senior, subsidized", Enabled = false, DisplayOrder = 69 },
                new AssistedWith { Id = 70, Code = "70", Description = "Housing (private)-assisted living", Enabled = false, DisplayOrder = 70 },
                new AssistedWith { Id = 71, Code = "71", Description = "Housing (private)-other", Enabled = false, DisplayOrder = 71 },
                new AssistedWith { Id = 72, Code = "72", Description = "Illini Dental", Enabled = true, DisplayOrder = 72 },
                new AssistedWith { Id = 73, Code = "73", Description = "Jones Optical", Enabled = true, DisplayOrder = 73 },
                new AssistedWith { Id = 74, Code = "74", Description = "Land of Lincoln Legal Assistance", Enabled = true, DisplayOrder = 74 },
                new AssistedWith { Id = 75, Code = "75", Description = "Lifeline-emergency response system", Enabled = true, DisplayOrder = 75 },
                new AssistedWith { Id = 76, Code = "76", Description = "Mental Health Center-Provena Behavioral Health", Enabled = true, DisplayOrder = 76 },
                new AssistedWith { Id = 77, Code = "77", Description = "Premier Choice", Enabled = false, DisplayOrder = 77 },
                new AssistedWith { Id = 78, Code = "78", Description = "Public Health Department", Enabled = false, DisplayOrder = 78 },
                new AssistedWith { Id = 79, Code = "79", Description = "Telephone discount programs", Enabled = true, DisplayOrder = 79 },
                new AssistedWith { Id = 80, Code = "80", Description = "other", Enabled = false, DisplayOrder = 80 },
                new AssistedWith { Id = 81, Code = "81", Description = "Staff initiated CB info", Enabled = false, DisplayOrder = 81 },
                new AssistedWith { Id = 82, Code = "82", Description = "Church Funds", Enabled = false, DisplayOrder = 82 },
                new AssistedWith { Id = 83, Code = "83", Description = "Nursing Home", Enabled = true, DisplayOrder = 83 },
                new AssistedWith { Id = 84, Code = "84", Description = "Lens Crafters-Gift of Sight", Enabled = false, DisplayOrder = 84 },
                new AssistedWith { Id = 85, Code = "85", Description = "Christie Hearing Services", Enabled = false, DisplayOrder = 85 },
                new AssistedWith { Id = 86, Code = "86", Description = "TANF", Enabled = true, DisplayOrder = 86 },
                new AssistedWith { Id = 87, Code = "87", Description = "Misc Client Assistance", Enabled = false, DisplayOrder = 87 },
                new AssistedWith { Id = 88, Code = "88", Description = "SPAP Information and Assistance Services", Enabled = false, DisplayOrder = 88 },
                new AssistedWith { Id = 89, Code = "89", Description = "SPAP Outreach Visits", Enabled = false, DisplayOrder = 89 },
                new AssistedWith { Id = 90, Code = "90", Description = "PEARLS", Enabled = false, DisplayOrder = 90 },
                new AssistedWith { Id = 91, Code = "91", Description = "Part D Enrollment Assistance", Enabled = false, DisplayOrder = 91 },
                new AssistedWith { Id = 92, Code = "92", Description = "Achieve Mobility Center", Enabled = false, DisplayOrder = 92 },
                new AssistedWith { Id = 93, Code = "93", Description = "Francis Nelson", Enabled = false, DisplayOrder = 93 },
                new AssistedWith { Id = 94, Code = "99", Description = "blank default", Enabled = false, DisplayOrder = 94 },
                new AssistedWith { Id = 95, Code = "112", Description = "SHAP Info and Assistance", Enabled = false, DisplayOrder = 100 },
                new AssistedWith { Id = 96, Code = "113", Description = "SHAP Counseling Services", Enabled = false, DisplayOrder = 113 },
                new AssistedWith { Id = 97, Code = "114", Description = "SHAP Outreach Visits", Enabled = false, DisplayOrder = 114 },
                new AssistedWith { Id = 98, Code = "115", Description = "Comp & Subm Extra Help Form", Enabled = false, DisplayOrder = 115 },
                new AssistedWith { Id = 99, Code = "117", Description = "Comp & Subm of Med D Plan Enrollment", Enabled = false, DisplayOrder = 116 },
                new AssistedWith { Id = 100, Code = "118", Description = "Comp & Subm CB/IL Cares RX/Other Rx Plan", Enabled = false, DisplayOrder = 118 },
                new AssistedWith { Id = 101, Code = "120", Description = "Additional Assistance MED D", Enabled = false, DisplayOrder = 119 },
                new AssistedWith { Id = 102, Code = "121", Description = "Additional Assistance IL Cares Rx", Enabled = false, DisplayOrder = 121 },
                new AssistedWith { Id = 103, Code = "122", Description = "Additional Assistance Medicare Advantage", Enabled = false, DisplayOrder = 122 },
                new AssistedWith { Id = 104, Code = "461", Description = "Grant/tax relief - agency - initiated outreach", Enabled = false, DisplayOrder = 123 },
                new AssistedWith { Id = 105, Code = "462", Description = "Grant/tax relief - help with form completion", Enabled = false, DisplayOrder = 462 },
                new AssistedWith { Id = 106, Code = "471", Description = "Pharmaceutical card - agency - initiated outreach", Enabled = false, DisplayOrder = 463 },
                new AssistedWith { Id = 107, Code = "472", Description = "Pharmaceutical card - help with form completion", Enabled = false, DisplayOrder = 472 },
                new AssistedWith { Id = 108, Code = "473", Description = "Douglas BEAM", Enabled = true, DisplayOrder = 473 },
                new AssistedWith { Id = 109, Code = "474", Description = "Douglas MSP", Enabled = true, DisplayOrder = 474 },
                new AssistedWith { Id = 110, Code = "475", Description = "Douglas Prescription Assistance ", Enabled = true, DisplayOrder = 475 },
                new AssistedWith { Id = 111, Code = "476", Description = "Douglas SHIP", Enabled = true, DisplayOrder = 476 },
                new AssistedWith { Id = 112, Code = "477", Description = "Champaign SHIP", Enabled = true, DisplayOrder = 477 },
                new AssistedWith { Id = 113, Code = "478", Description = "Disability Services", Enabled = true, DisplayOrder = 478 },
                new AssistedWith { Id = 114, Code = "479", Description = "Dementia Resources", Enabled = true, DisplayOrder = 479 },
                new AssistedWith { Id = 115, Code = "480", Description = "End of Life Planning", Enabled = true, DisplayOrder = 480 },
                new AssistedWith { Id = 116, Code = "481", Description = "Hearing Assistance", Enabled = true, DisplayOrder = 481 },
                new AssistedWith { Id = 117, Code = "482", Description = "Pets", Enabled = true, DisplayOrder = 482 },
                new AssistedWith { Id = 118, Code = "483", Description = "Socialization", Enabled = true, DisplayOrder = 483 }
            );
        }
    }
}