using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FSSRC_DataMigration.DestinationEntity
{
    public class SIS : BaseLookupEntity
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }

    class SISConfig : IEntityTypeConfiguration<SIS>
    {
        public void Configure(EntityTypeBuilder<SIS> entity)
        {
            entity.HasData(
                new SIS { Id = 1, Code = "1", Description = "Outreach", DisplayOrder = 1, Enabled = true },
                new SIS { Id = 2, Code = "2", Description = "Counseling", DisplayOrder = 2, Enabled = true },
                new SIS { Id = 3, Code = "3", Description = "Elder Abuse", DisplayOrder = 3, Enabled = true },
                new SIS { Id = 4, Code = "4", Description = "Transportation", DisplayOrder = 4, Enabled = true },
                new SIS { Id = 5, Code = "5", Description = "Meals on Wheels", DisplayOrder = 5, Enabled = true },
                new SIS { Id = 6, Code = "6", Description = "Reassurance Calling", DisplayOrder = 6, Enabled = true },
                new SIS { Id = 7, Code = "7", Description = "Friendly visitor", DisplayOrder = 7, Enabled = true },
                new SIS { Id = 8, Code = "8", Description = "HomeCare Private Pay", DisplayOrder = 8, Enabled = true },
                new SIS { Id = 9, Code = "9", Description = "Lions Club", DisplayOrder = 9, Enabled = true },
                new SIS { Id = 10, Code = "10", Description = "Rent assistance", DisplayOrder = 10, Enabled = true },
                new SIS { Id = 11, Code = "11", Description = "Utility assistance", DisplayOrder = 11, Enabled = true },
                new SIS { Id = 12, Code = "12", Description = "Prescription assistance", DisplayOrder = 12, Enabled = true },
                new SIS { Id = 13, Code = "13", Description = "Food assistance", DisplayOrder = 13, Enabled = true },
                new SIS { Id = 14, Code = "14", Description = "First Call for Help-other", DisplayOrder = 14, Enabled = true },
                new SIS { Id = 15, Code = "15", Description = "Food for Seniors", DisplayOrder = 15, Enabled = true },
                new SIS { Id = 16, Code = "16", Description = "Volunteer opportunity", DisplayOrder = 16, Enabled = true },
                new SIS { Id = 17, Code = "17", Description = "Caregiver Advisory Service-Caregiver", DisplayOrder = 17, Enabled = true },
                new SIS { Id = 18, Code = "18", Description = "Caregiver Advisory Service-GRG", DisplayOrder = 18, Enabled = true },
                new SIS { Id = 19, Code = "19", Description = "Self-Help Center", DisplayOrder = 19, Enabled = true },
                new SIS { Id = 20, Code = "20", Description = "Adult day care", DisplayOrder = 20, Enabled = true },
                new SIS { Id = 21, Code = "21", Description = "Homemaker", DisplayOrder = 21, Enabled = true },
                new SIS { Id = 22, Code = "22", Description = "Home repair", DisplayOrder = 22, Enabled = true },
                new SIS { Id = 23, Code = "23", Description = "CCU-other", DisplayOrder = 23, Enabled = true },
                new SIS { Id = 24, Code = "24", Description = "Homestead exemption", DisplayOrder = 24, Enabled = true },
                new SIS { Id = 25, Code = "25", Description = "Tax deferral program", DisplayOrder = 25, Enabled = true },
                new SIS { Id = 26, Code = "26", Description = "Tax freeze", DisplayOrder = 26, Enabled = true },
                new SIS { Id = 27, Code = "27", Description = "Food Pantry", DisplayOrder = 27, Enabled = true },
                new SIS { Id = 28, Code = "28", Description = "Transportation", DisplayOrder = 28, Enabled = true },
                new SIS { Id = 29, Code = "29", Description = "Gap filling", DisplayOrder = 29, Enabled = true },
                new SIS { Id = 30, Code = "30", Description = "Ombudsman", DisplayOrder = 30, Enabled = true },
                new SIS { Id = 31, Code = "31", Description = "Farmers' Market Coupons", DisplayOrder = 31, Enabled = true },
                new SIS { Id = 32, Code = "32", Description = "Food", DisplayOrder = 32, Enabled = true },
                new SIS { Id = 33, Code = "33", Description = "Money", DisplayOrder = 33, Enabled = true },
                new SIS { Id = 34, Code = "34", Description = "Furniture/Clothes", DisplayOrder = 34, Enabled = true },
                new SIS { Id = 35, Code = "35", Description = "Food", DisplayOrder = 35, Enabled = true },
                new SIS { Id = 36, Code = "36", Description = "Holiday program", DisplayOrder = 36, Enabled = true },
                new SIS { Id = 37, Code = "37", Description = "Fraternal Order of Police-Other", DisplayOrder = 37, Enabled = true },
                new SIS { Id = 38, Code = "38", Description = "Senior apartments", DisplayOrder = 38, Enabled = true },
                new SIS { Id = 39, Code = "39", Description = "Section 8 vouchers", DisplayOrder = 39, Enabled = true },
                new SIS { Id = 40, Code = "40", Description = "AABD CASH/Link card", DisplayOrder = 40, Enabled = true },
                new SIS { Id = 41, Code = "41", Description = "Food Stamps/Link card", DisplayOrder = 41, Enabled = true },
                new SIS { Id = 42, Code = "42", Description = "Qualified Medicare Beneficiary (QMB) or SLIB", DisplayOrder = 42, Enabled = true },
                new SIS { Id = 43, Code = "43", Description = "Medicaid application/re-certification", DisplayOrder = 43, Enabled = true },
                new SIS { Id = 44, Code = "44", Description = "Medicaid Spend-down assistance", DisplayOrder = 44, Enabled = true },
                new SIS { Id = 45, Code = "45", Description = "Medicaid Spousal Impoverishment", DisplayOrder = 45, Enabled = true },
                new SIS { Id = 46, Code = "46", Description = "Circuit Breaker-grant/tax relief", DisplayOrder = 46, Enabled = true },
                new SIS { Id = 47, Code = "47", Description = "Circuit Breaker-pharmaceutical card", DisplayOrder = 47, Enabled = true },
                new SIS { Id = 48, Code = "48", Description = "Congregate meal site", DisplayOrder = 48, Enabled = true },
                new SIS { Id = 49, Code = "49", Description = "Home-delivered meals", DisplayOrder = 49, Enabled = true },
                new SIS { Id = 50, Code = "50", Description = "Warm Neighbors", DisplayOrder = 50, Enabled = true },
                new SIS { Id = 51, Code = "51", Description = "Holiday voucher", DisplayOrder = 51, Enabled = true },
                new SIS { Id = 52, Code = "52", Description = "Social services", DisplayOrder = 52, Enabled = true },
                new SIS { Id = 53, Code = "53", Description = "Elder Care", DisplayOrder = 53, Enabled = true },
                new SIS { Id = 54, Code = "54", Description = "Home repair", DisplayOrder = 54, Enabled = true },
                new SIS { Id = 55, Code = "55", Description = "Money management", DisplayOrder = 55, Enabled = true },
                new SIS { Id = 56, Code = "56", Description = "Rural transportation", DisplayOrder = 56, Enabled = true },
                new SIS { Id = 57, Code = "57", Description = "Senior Services- other", DisplayOrder = 57, Enabled = true },
                new SIS { Id = 58, Code = "58", Description = "Social Security (SSA): Retirement", DisplayOrder = 58, Enabled = true },
                new SIS { Id = 59, Code = "59", Description = "Social Security (SSA): Disability", DisplayOrder = 59, Enabled = true },
                new SIS { Id = 60, Code = "60", Description = "Supplemental Security Income (SSI): 65+", DisplayOrder = 60, Enabled = true },
                new SIS { Id = 61, Code = "61", Description = "Supplemental Security Income (SSI): Disability", DisplayOrder = 61, Enabled = true },
                new SIS { Id = 62, Code = "62", Description = "Medicare", DisplayOrder = 62, Enabled = true },
                new SIS { Id = 63, Code = "63", Description = "Appeal", DisplayOrder = 63, Enabled = true },
                new SIS { Id = 64, Code = "64", Description = "Senior Employment Program", DisplayOrder = 64, Enabled = true },
                new SIS { Id = 65, Code = "65", Description = "Seniors in Community Service Program", DisplayOrder = 65, Enabled = true },
                new SIS { Id = 66, Code = "66", Description = "LIHEAP", DisplayOrder = 66, Enabled = true },
                new SIS { Id = 67, Code = "67", Description = "Weatherization/furnace repair", DisplayOrder = 67, Enabled = true },
                new SIS { Id = 68, Code = "68", Description = "Alzheimer's Association", DisplayOrder = 68, Enabled = true },
                new SIS { Id = 69, Code = "69", Description = "Housing (private)-senior, subsidized", DisplayOrder = 69, Enabled = true },
                new SIS { Id = 70, Code = "70", Description = "Housing (private)-assisted living", DisplayOrder = 70, Enabled = true },
                new SIS { Id = 71, Code = "71", Description = "Housing (private)-other", DisplayOrder = 71, Enabled = true },
                new SIS { Id = 72, Code = "72", Description = "Illini Dental", DisplayOrder = 72, Enabled = true },
                new SIS { Id = 73, Code = "73", Description = "Jones Optical", DisplayOrder = 73, Enabled = true },
                new SIS { Id = 74, Code = "74", Description = "Land of Lincoln Legal Assistance", DisplayOrder = 74, Enabled = true },
                new SIS { Id = 75, Code = "75", Description = "Lifeline-emergency response system", DisplayOrder = 75, Enabled = true },
                new SIS { Id = 76, Code = "76", Description = "Mental Health Center-Provena Behavioral Health", DisplayOrder = 76, Enabled = true },
                new SIS { Id = 77, Code = "77", Description = "Premier Choice", DisplayOrder = 77, Enabled = true },
                new SIS { Id = 78, Code = "78", Description = "Public Health Department", DisplayOrder = 78, Enabled = true },
                new SIS { Id = 79, Code = "79", Description = "Telephone discount programs", DisplayOrder = 79, Enabled = true },
                new SIS { Id = 80, Code = "80", Description = "other", DisplayOrder = 80, Enabled = true },
                new SIS { Id = 81, Code = "81", Description = "Staff initiated CB info", DisplayOrder = 81, Enabled = true },
                new SIS { Id = 82, Code = "82", Description = "Church Funds", DisplayOrder = 82, Enabled = true },
                new SIS { Id = 83, Code = "83", Description = "Nursing Home", DisplayOrder = 83, Enabled = true },
                new SIS { Id = 84, Code = "84", Description = "Lens Crafters-Gift of Sight", DisplayOrder = 84, Enabled = true },
                new SIS { Id = 85, Code = "85", Description = "Christie Hearing Services", DisplayOrder = 85, Enabled = true },
                new SIS { Id = 86, Code = "86", Description = "TANF", DisplayOrder = 86, Enabled = true },
                new SIS { Id = 87, Code = "87", Description = "Misc Client Assistance", DisplayOrder = 87, Enabled = true },
                new SIS { Id = 88, Code = "88", Description = "SPAP Information and Assistance Services", DisplayOrder = 88, Enabled = true },
                new SIS { Id = 89, Code = "89", Description = "SPAP Outreach Visits", DisplayOrder = 89, Enabled = true },
                new SIS { Id = 90, Code = "90", Description = "PEARLS", DisplayOrder = 90, Enabled = true },
                new SIS { Id = 91, Code = "91", Description = "Part D Enrollment Assistance", DisplayOrder = 91, Enabled = true },
                new SIS { Id = 92, Code = "92", Description = "Achieve Mobility Center", DisplayOrder = 92, Enabled = true },
                new SIS { Id = 93, Code = "93", Description = "Francis Nelson", DisplayOrder = 93, Enabled = true },
                new SIS { Id = 94, Code = "99", Description = "blank default", DisplayOrder = 94, Enabled = true },
                new SIS { Id = 95, Code = "112", Description = "SHAP Info and Assistance", DisplayOrder = 95, Enabled = true },
                new SIS { Id = 96, Code = "113", Description = "SHAP Counseling Services", DisplayOrder = 96, Enabled = true },
                new SIS { Id = 97, Code = "114", Description = "SHAP Outreach Visits", DisplayOrder = 97, Enabled = true },
                new SIS { Id = 98, Code = "115", Description = "Comp & Subm Extra Help Form", DisplayOrder = 98, Enabled = true },
                new SIS { Id = 99, Code = "117", Description = "Comp & Subm of Med D Plan Enrollment", DisplayOrder = 99, Enabled = true },
                new SIS { Id = 100, Code = "118", Description = "Comp & Subm CB/IL Cares RX/Other Rx Plan", DisplayOrder = 100, Enabled = true },
                new SIS { Id = 101, Code = "120", Description = "Additional Assistance MED D", DisplayOrder = 101, Enabled = true },
                new SIS { Id = 102, Code = "121", Description = "Additional Assistance IL Cares Rx", DisplayOrder = 102, Enabled = true },
                new SIS { Id = 103, Code = "122", Description = "Additional Assistance Medicare Advantage", DisplayOrder = 103, Enabled = true },
                new SIS { Id = 104, Code = "461", Description = "Grant/tax relief - agency - initiated outreach", DisplayOrder = 104, Enabled = true },
                new SIS { Id = 105, Code = "462", Description = "Grant/tax relief - help with form completion", DisplayOrder = 105, Enabled = true },
                new SIS { Id = 106, Code = "471", Description = "Pharmaceutical card - agency - initiated outreach", DisplayOrder = 106, Enabled = true },
                new SIS { Id = 107, Code = "472", Description = "Pharmaceutical card - help with form completion", DisplayOrder = 107, Enabled = true }
            );
        }
    }
}