SELECT 
  lngTransportActivity_id AS Id, 
  CAST(1 as bit) AS Enabled, 
  datTransport_dt AS Date, 
  datTransport_dt + ' ' + datTransport_tm AS Time, 
  lngEmp_id AS StaffId, 
  CASE vchTransportMode_cd WHEN 'aTAXI Orange' THEN 1 WHEN 'bVOL' THEN 2 WHEN 'cTAXI Yellow' THEN 3 WHEN 'dAtlas' THEN 4 WHEN 'ORANGE' THEN 5 WHEN 'VOL' THEN 6 WHEN 'Cancelled' THEN 7 WHEN 'CORKYS' THEN 8 WHEN 'CUDELIVERY' THEN 9 WHEN 'zHC-CCP' THEN 10 WHEN 'HC-PP' THEN 11 WHEN 'MOMMIES' THEN 12 WHEN 'NORIDE' THEN 13 WHEN 'zORANGE' THEN 14 WHEN 'SPECCARE' THEN 15 WHEN 'zSTAFF' THEN 16 WHEN 'WECARE' THEN 17 WHEN 'TAXI' THEN 18 WHEN 'aTAXI' THEN 19 WHEN 'VAN' THEN 20 WHEN 'STAFF' THEN 21 ELSE NULL END AS ModeId, 
  CASE vchTransportReason_cd WHEN 'BUSINESS' THEN 1 WHEN 'GROCERY' THEN 2 WHEN 'MEDICAL' THEN 3 WHEN 'Q.O.L.' THEN 4 ELSE NULL END AS ReasonId, 
  CAST(bytOneWayRide_amt as INT) AS RideId, 
  CASE vchTransportDestination_desc WHEN 'Aldi Foods' THEN 1 WHEN 'County Market' THEN 3 WHEN 'Walmart' THEN 6 WHEN 'zz Provena Covenant Medical Center' THEN 7 WHEN 'zz Carle Foundation Hospital' THEN 8 WHEN 'zz Illini Dental' THEN 9 WHEN 'zz Dr. Wrestler & Associates' THEN 10 WHEN 'zz Christie--University' THEN 11 WHEN 'zz Christie-- Urbana' THEN 12 WHEN 'zz Christie-- Kirby & Duncan' THEN 13 WHEN 'zz Christie-- Cancer Center' THEN 14 WHEN 'zz Christie-- CU Sleep' THEN 15 WHEN 'zz Christie -- Windsor' THEN 16 WHEN 'zz CarleClinic-- Rantoul' THEN 17 WHEN 'zz Carle Clinic--Curtis Road' THEN 18 WHEN 'zz Carle Clinic--Windsor, Urbana' THEN 19 WHEN 'zz Carle Clinic--SE Urbana' THEN 20 WHEN 'zz Carle Clinic--Urbana Main' THEN 21 WHEN 'zz Carle Heart Center' THEN 22 WHEN 'zz Carle Spine Institute' THEN 23 WHEN 'zz Carle Cancer Center' THEN 24 WHEN 'zz Carle Wound Clinic' THEN 25 WHEN 'Target' THEN 26 WHEN 'zz Pharmacy' THEN 27 WHEN 'Bank' THEN 28 WHEN 'Dentist' THEN 29 WHEN 'Doctor' THEN 30 WHEN 'zz Church' THEN 31 WHEN 'Nursing Home' THEN 32 WHEN 'zz Adult Day Care' THEN 33 WHEN 'zz Library' THEN 34 WHEN 'Hairdresser/Manicure' THEN 35 WHEN 'Volunteer/Work' THEN 36 WHEN 'Frances Nelson' THEN 37 WHEN 'zz Widick Foot Clinic' THEN 38 WHEN 'CU Dialysis' THEN 39 WHEN 'MTD' THEN 40 WHEN 'zz Carle -- Pavillion' THEN 41 WHEN 'zz Provena Partners' THEN 42 WHEN 'Other -- Business' THEN 43 WHEN 'Other -- QOL' THEN 44 WHEN 'zz Carle-- Clinic' THEN 45 WHEN 'Other -- Medical' THEN 46 WHEN 'zz Carle-- Windsor and Duncan' THEN 47 WHEN 'Provena' THEN 48 WHEN 'Carle' THEN 49 WHEN 'Christie' THEN 50 WHEN 'Carle - Rantoul' THEN 51 WHEN 'zz Pavillion' THEN 52 WHEN 'Christie - Mahomet' THEN 53 WHEN 'Muscatella Family Foot' THEN 54 WHEN 'zz Optical NS' THEN 55 WHEN 'zz CVS' THEN 56 WHEN 'Walgreens' THEN 57 WHEN 'Eye Center' THEN 58 WHEN 'Other - Grocery' THEN 59 WHEN 'zz Champaign Dental' THEN 60 WHEN 'zz Hearing NS' THEN 61 WHEN 'zz Dentistry by Design' THEN 62 WHEN 'Aspen Dental' THEN 63 WHEN 'zz Audibel' THEN 64 WHEN 'zz Busey Bank' THEN 65 WHEN 'Bayview Family Clinic' THEN 66 WHEN 'zz Bo Ric' THEN 67 WHEN 'zz Family Dental' THEN 68 WHEN 'zzHanger Orthopedic' THEN 69 WHEN 'Community Elements' THEN 70 WHEN 'zz Regional Planning' THEN 71 WHEN 'Social Security' THEN 72 WHEN 'DHS' THEN 73 WHEN 'zz Retina of Illinois' THEN 74 WHEN 'Davita Dialysis' THEN 75 WHEN 'zz Dankle, Brunson and Lee Dentistry' THEN 76 WHEN 'zz CU Dental' THEN 77 WHEN 'DMV' THEN 78 WHEN 'OSF' THEN 79 WHEN 'Rosecrance' THEN 80 ELSE 81 END AS DestinationId, 
  CAST(CASE bitLateRequest_flag WHEN 0 THEN 0 ELSE 1 END as bit) AS IsLateRequest, 
  lngClient_id AS TransportationRecordId 
FROM 
  dbo.transportActivity
